name: car_rental_app
description: A simple car rental app demonstrating Flutter widgets
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.19.0
  firebase_core: ^2.17.2
  cloud_firestore: ^4.8.0  # Проверь, что эта версия актуальна
  firebase_analytics: ^10.0.0
  firebase_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/banner.png
    - assets/images/cars/