// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMRn2IBufC7XVCCAw8hYO9gDm3zmfQOCQ',
    appId: '1:379766117798:web:945d03377b4e7ad12deb67',
    messagingSenderId: '379766117798',
    projectId: 'newcarrent-53113',
    authDomain: 'newcarrent-53113.firebaseapp.com',
    storageBucket: 'newcarrent-53113.firebasestorage.app',
    measurementId: 'G-Q5DJTNQPHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM7V6gbtqYt3UN-kdIuRRvArhrZQhHLm8',
    appId: '1:379766117798:android:124200bea8445ca82deb67',
    messagingSenderId: '379766117798',
    projectId: 'newcarrent-53113',
    storageBucket: 'newcarrent-53113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6dHQKUgAsP1BRaeOlBAEQBx5rRZMpDsQ',
    appId: '1:379766117798:ios:d77aad63f515b9902deb67',
    messagingSenderId: '379766117798',
    projectId: 'newcarrent-53113',
    storageBucket: 'newcarrent-53113.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6dHQKUgAsP1BRaeOlBAEQBx5rRZMpDsQ',
    appId: '1:379766117798:ios:d77aad63f515b9902deb67',
    messagingSenderId: '379766117798',
    projectId: 'newcarrent-53113',
    storageBucket: 'newcarrent-53113.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMRn2IBufC7XVCCAw8hYO9gDm3zmfQOCQ',
    appId: '1:379766117798:web:3df85195f609e2a12deb67',
    messagingSenderId: '379766117798',
    projectId: 'newcarrent-53113',
    authDomain: 'newcarrent-53113.firebaseapp.com',
    storageBucket: 'newcarrent-53113.firebasestorage.app',
    measurementId: 'G-NWNT1CDRXS',
  );

}